# Generated by Django 3.2 on 2022-11-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('user_image', models.ImageField(upload_to='image/')),
                ('introduce', models.FileField(upload_to='introduce/')),
            ],
        ),
    ]
