# Generated by Django 3.2 on 2022-11-28 08:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('upload_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='upload_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
