# Generated by Django 3.2 on 2022-11-28 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_profile', '0002_user_upload_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Photo',
        ),
    ]
