# Generated by Django 3.2 on 2022-11-30 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_profile', '0003_rename_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='user_image',
            field=models.ImageField(upload_to='static/main/image/'),
        ),
    ]
