# Generated by Django 3.2 on 2022-11-30 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_profile', '0004_alter_photo_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='user_image',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
