# Generated by Django 3.2 on 2022-11-26 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
